# Generated by Django 3.0 on 2021-03-25 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 17, 19, 28, 466526, tzinfo=utc)),
        ),
    ]
