# Generated by Django 3.0 on 2021-03-26 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0005_auto_20210326_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 10, 2, 4, 399427, tzinfo=utc)),
        ),
    ]
