# Generated by Django 3.0 on 2021-03-26 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0014_auto_20210326_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expiration',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 11, 5, 4, 908238, tzinfo=utc)),
        ),
    ]
