# Generated by Django 3.0 on 2021-03-26 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0016_auto_20210326_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 14, 32, 51, 903967, tzinfo=utc)),
        ),
    ]
