# Generated by Django 3.0 on 2021-03-26 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0017_auto_20210326_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 14, 34, 59, 826314, tzinfo=utc)),
        ),
    ]
