# Generated by Django 3.0 on 2021-03-30 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import piazza.models


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0020_auto_20210326_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='piazza.Post', validators=[piazza.models.validate_islive]),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='piazza.Post', validators=[piazza.models.validate_islive]),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 13, 24, 36, 856583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
    ]
