# Generated by Django 3.0 on 2021-03-30 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0021_auto_20210330_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 13, 28, 22, 514537, tzinfo=utc)),
        ),
    ]
